### ISSUE TITLE
Internal server error: MalformedFileError: First record is not a Compound Tag

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#18] opened 2022-07-14 16:28 UTC
**Feature branch: `None`**

This is a common exception (likely caused by an unloaded chunk) and should be handled.
Optionally, one could make use of the `/forceload` command to keep chunks loaded within the build area (might be a good idea to include that in the interface)

**Comment by avdstaaij** [comment] 2023-02-28 00:25
I cannot reproduce this bug. Even when working with a build area 100,000 blocks away, everything seems to work just fine. I suspect that the bug has been solved somewhere along the way, either in GDPC or in GDMC-HTTP. I'm closing this issue, but feel free to open a new one if the bug still occurs.

**Closed by avdstaaij** 2023-02-28 00:25 UTC
Labels: bug
